version: '3.7'
services:
  proxy:
    image: nginx:1.13
    volumes:
      - ./config/proxy:/etc/nginx/conf.d
    ports:
      - "443:443"
  mocklogin:
    image: lblod/mock-login-service:0.7.0
    environment:
      GROUP_TYPE: "http://www.w3.org/ns/org#Organization"
  subsidy-applications-retrieval:
    image: lblod/subsidy-applications-retrieval-service:0.1.2
    volumes:
      - ./config/subsidy-application-management:/config
    restart: "no"
  impersonation:
    restart: "no"

  frontend:
    restart: "no"
    environment:
      EMBER_FEATURE_PUBLIC_SERVICES_ENABLED: "true"
      EMBER_FEATURE_EREDIENSTEN_MANDATENBEHEER_ENABLED: "true"
      EMBER_FEATURE_WORSHIP_MINISTER_MANAGEMENT_ENABLED: "true"
      EMBER_WORSHIP_DECISIONS_DATABASE_URL: "https://dev.databankerediensten.lokaalbestuur.lblod.info"
      EMBER_WORSHIP_ORGANISATIONS_DATABASE_URL: "https://dev.organisaties.lokaalbestuur.lblod.info"
    ports:
      - "80:80"
  frontend-subsidiedatabank:
    restart: "no"
    ports:
      - "85:80"
  identifier:
    ports:
      - "90:80"
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  op-public-consumer:
    restart: "no"
  deltanotifier:
    restart: "no"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  db-cleanup:
    restart: "no"
  login:
    restart: "no"
  file:
    restart: "no"
  deliver-email-service:
    restart: "no"
  report-generation:
    restart: "no"
  subsidy-applications-management:
    environment:
      VERSIONED_CONFIGURATION_WATCHER: null
    restart: "no"
  case-number-generator:
    restart: "no"
  subsidy-application-flow-management:
    restart: "no"
  publication-triplestore:
    restart: "no"
    ports:
      - "8891:8890"
  delta-producer-report-generator:
    restart: "no"
  delta-producer-dump-file-publisher:
    restart: "no"
  error-alert:
    environment:
      EMAIL_FROM: "Subsidiepunt Local <subsidiepunt-development@redpencil.io>"
      EMAIL_TO: "subsidiepunt-development@redpencil.io"
    restart: "no"
  mock-account-generation:
    restart: "no"
  ldes-delta-pusher:
    restart: "no"
    environment:
      DEBUG: "true"
      LDES_BASE: "http://localhost:90/streams/ldes/subsidies"
  ldes-backend:
    restart: "no"
    environment:
      BASE_URL: "http://localhost:90/streams/ldes/subsidies/"
      LDES_STREAM_PREFIX: "http://localhost:90/streams/ldes/subsidies/"

  form-data-management:
    restart: "no"