DELETE {
  GRAPH ?preFusionGraph {
    ?s ?p ?o
  }
}
WHERE {
  VALUES ?preFusionGraph {
     # Beveren - gemeente
     <http://mu.semte.ch/graphs/organizations/4f0eb4436c88cf831c35f84e7c34ce32f9ee4e99c5139aff62990e5e531aa1e7/SubsidiepuntGebruiker>
     # Beveren - ocmw
     <http://mu.semte.ch/graphs/organizations/72bc672ceb6894d8dd31dc2dff2faad2fd93f4b9f5347d556d092516eaa30aa3/SubsidiepuntGebruiker>
     # Kruibeke - gemeente
     <http://mu.semte.ch/graphs/organizations/6af55cecaea3621f53bb32417a36ed6e3d41b2aa5b9f6d62ab3d80cc8ec11539/SubsidiepuntGebruiker>
     # Kruibeke - ocmw
     <http://mu.semte.ch/graphs/organizations/d3c76fd84794dad5e12c9eed6d6332dc5e5c99daf0e4ddd7ceebf13d5d6c0ccd/SubsidiepuntGebruiker>
     # Zwijndrecht - gemeente
     <http://mu.semte.ch/graphs/organizations/c362abc58ac4579ff417824ce620962ac57bc344b34fe8f51d21b35ef54da36d/SubsidiepuntGebruiker>
     # Zwijndrecht - ocmw
     <http://mu.semte.ch/graphs/organizations/bbc23313f4c8585a0c51f15f920d77123356535cd1cad9af38f5707892c7088d/SubsidiepuntGebruiker>

     # Bilzen-Hoeselt
     # Hoeselt - gemeente
     <http://mu.semte.ch/graphs/organizations/a3bd0845853278f478f90b14436d3efa99e73249a84d462f0ddc2e5b6e37a156/SubsidiepuntGebruiker>
     # Hoeselt - ocmw
     <http://mu.semte.ch/graphs/organizations/785e8d5516378c7382ad0e7e356d2301496d810c6cd46d72ccebb455d3ac525e/SubsidiepuntGebruiker>

     # Tongeren-Borgloon
     # Borgloon - gemeente
     <http://mu.semte.ch/graphs/organizations/05441122597e0b20b61a8968ea1247c07f9014aad1f1f0709d0b1234e3dfbc2f/SubsidiepuntGebruiker>
     # Borgloon - ocmw
     <http://mu.semte.ch/graphs/organizations/3834647b5e95ea20f5ffe5a12a09fbd3d7fdf0d187fab385cb7b841422176ad6/SubsidiepuntGebruiker>

     # Nazareth-De Pinte
     # Nazareth - gemeente
     <http://mu.semte.ch/graphs/organizations/0327a51548f73607f8a5ec11b36711a3c96703686ad93a3d632718c135c295db/SubsidiepuntGebruiker>
     # Nazareth - ocmw
     <http://mu.semte.ch/graphs/organizations/0a2d980559eb9f3e0820386541274a72692f495204cd6d951ea1907ecc65829b/SubsidiepuntGebruiker>
     # De Pinte - gemeente
     <http://mu.semte.ch/graphs/organizations/e39bc997aa6dd9f240277735efd745b6a0422614d2b36cf01825c86b1b91a9ee/SubsidiepuntGebruiker>
     # De Pinte - ocmw
     <http://mu.semte.ch/graphs/organizations/144c75e403c5084af57f5c0c86252b8759b56baf9694326abbcb5ea40ab69f1a/SubsidiepuntGebruiker>

     # Pajottegem
     # Galmaarden - gemeente
     <http://mu.semte.ch/graphs/organizations/00eb231f51bd6b4f5dcc6536b2d09a174ea8583f5bf28b10bc4fc769a07e511d/SubsidiepuntGebruiker>
     # Galmaarden - ocmw
     <http://mu.semte.ch/graphs/organizations/ba8a253d98ea7d2ab1afc43e5e2cd145a12ccd86b68e71d023e3c13a83d7498f/SubsidiepuntGebruiker>
     # Gooik - gemeente
     <http://mu.semte.ch/graphs/organizations/c69192b973a3ca11531b9657b3ee20aa6688fa33ea1ef1392310fec751980ab2/SubsidiepuntGebruiker>
     # Gooik - ocmw
     <http://mu.semte.ch/graphs/organizations/76c45d60f05bf8afc8c71859342b69cac6a57ee2b320b900a60afd6ba9b8eb9d/SubsidiepuntGebruiker>
     # Herne - gemeente
     <http://mu.semte.ch/graphs/organizations/3eb8c9fae32d02359dcd7b22e2a74e67a5b48388df31ad819c27c688fedd10b0/SubsidiepuntGebruiker>
     # Herne - ocmw
     <http://mu.semte.ch/graphs/organizations/5d21ccef2f5aa3ccbf3a74c6f25ebe9f0b1ef5a97b87f3d79c86ae9d6d857df8/SubsidiepuntGebruiker>

     # Tessenderlo-Ham
     # Tessenderlo - gemeente
     <http://mu.semte.ch/graphs/organizations/af8969752f6b28c66b6bc402d7987fa38774901ac72b95c5cb7976570487c3c9/SubsidiepuntGebruiker>
     # Tessenderlo - ocmw
     <http://mu.semte.ch/graphs/organizations/fb1be873c4b31e391613dfae8e68edd694b1fdf126eeecb502b1e5cad6f2f682/SubsidiepuntGebruiker>

     # Hasselt
     # Kortessem - gemeente
     <http://mu.semte.ch/graphs/organizations/f6b131de5e40a0dfd4fc93fedf3b95c9bf156ece718b87fe00469dea2564b3fb/SubsidiepuntGebruiker>
     # Kortessem - ocmw
     <http://mu.semte.ch/graphs/organizations/3e077115eeb70b649d44e2ebbb218f2cfcac5d84e130c88584f0ec23f7cebbf9/SubsidiepuntGebruiker>

     # Lochistri
     # Wachtebeke - gemeente
     <http://mu.semte.ch/graphs/organizations/1313d4a58f9ecf52cc7e274e3549a759b35e731973cc9f5e07562e5650f594dd/SubsidiepuntGebruiker>
     # Wachtebeke - ocmw
     <http://mu.semte.ch/graphs/organizations/7c6b38fa6fc65879cb674a654617de171adfcfacba086fb918da3749dbaa43b5/SubsidiepuntGebruiker>

     # Lokeren
     # Moerbeke - gemeente
     <http://mu.semte.ch/graphs/organizations/c5dbb08e35e2d090a05d119fef4cc161b5ee1f322698cb8ea3c8c6643a521cf2/SubsidiepuntGebruiker>
     # Moerbeke - ocmw
     <http://mu.semte.ch/graphs/organizations/f2a9a2392d5e4c0f992a84a0871d048a7b91b14681e9980a63aa6ba4b1f7eb8c/SubsidiepuntGebruiker>

     # Merelbeke-Melle
     # Melle - gemeente
     <http://mu.semte.ch/graphs/organizations/c0b6b5cf198cd939251dff8ed052177cfff245074c6b8d43394c8c97f7b6e945/SubsidiepuntGebruiker>
     # Melle - ocmw
     <http://mu.semte.ch/graphs/organizations/04895013fe6301f32aa46deae98abfb833a717ece5a33b6c453674c6d0f4cc5e/SubsidiepuntGebruiker>
     # Merelbeke - gemeente
     <http://mu.semte.ch/graphs/organizations/8ef1e4a43efd913e6b09b0ddea344b7b5d723a344ad559389a55ae1ff0bebc8f/SubsidiepuntGebruiker>
     # Merelbeke - ocmw
     <http://mu.semte.ch/graphs/organizations/f56f068943a99059f5bfc3b905fe8848a25a47cfa30fb3ed3d294b47815b2255/SubsidiepuntGebruiker>

     # Tielt
     # Meulebeke - gemeente
     <http://mu.semte.ch/graphs/organizations/5a4b2b4f1de1f3b91b0348a7eb6d6aa0ef9420b8ec31374970c9ffe933a79515/SubsidiepuntGebruiker>
     # Meulebeke - ocmw
     <http://mu.semte.ch/graphs/organizations/3f57a17fbcdfc13def910c54948bec11d71d3f75946b0336fffc0587bf18d783/SubsidiepuntGebruiker>

     # Wingene
     # Ruiselede - gemeente
     <http://mu.semte.ch/graphs/organizations/2564e21e3650f91625189ccb7eb055e47754a0633c54c7582a899171fef60c52/SubsidiepuntGebruiker>
     # Ruiselede - ocmw
     <http://mu.semte.ch/graphs/organizations/60daf27c2cf12dd123447aa300dd7320890391dbd8dd6b4dd7ec02258f8281b3/SubsidiepuntGebruiker>

     # Antwerpen
     # Borsbeek - gemeente
     <http://mu.semte.ch/graphs/organizations/e41ffa04f94bb450a79793020e70d55b5fee5033a5280277998608a9d0913117/SubsidiepuntGebruiker>
     # Borsbeek - ocmw
     <http://mu.semte.ch/graphs/organizations/7125fcbfb7a08f8c01efbed115cea602db249c04afe9b5a2cc298cc7949cd040/SubsidiepuntGebruiker>
   }

  GRAPH ?g {
    ?s ?p ?o.
  }

  GRAPH ?preFusionGraph {
    ?s ?p ?o.
  }

  FILTER(REGEX(STR(?g), "^http://mu.semte.ch/graphs/organizations/.+/SubsidiepuntGebruiker$"))
  FILTER(?g != ?preFusionGraph)
}