# Potentially too much data could habe been deleted due to delta-consumer mapping config issues.
# This migration ensures target graph is in sync again.
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://www.w3.org/ns/org#Organization> ;
      ?p ?o .
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/landing-zone/op-public> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> .

    FILTER NOT EXISTS {
      VALUES ?type {
        <http://data.lblod.info/vocabularies/erediensten/BestuurVanDeEredienst>
        <http://data.lblod.info/vocabularies/erediensten/CentraalBestuurVanDeEredienst>
        <http://data.lblod.info/vocabularies/erediensten/RepresentatiefOrgaan>
      }

      ?s ?p ?o .
    }

    FILTER (?p NOT IN (<http://www.w3.org/ns/adms#identifier>, <http://www.w3.org/ns/org#classification>))
  }
}
