INSERT {
  GRAPH ?g {
    ?formData a <http://lblod.data.gift/vocabularies/subsidie/attachment/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/attachment> ?formData .
    ?formData ?p ?o .
    FILTER NOT EXISTS {
      ?formData a <http://lblod.data.gift/vocabularies/subsidie/attachment/FormData> .
    }
  }
}
;
INSERT {
  GRAPH ?g {
    ?politicalReferenceContactPoint <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://mu.semte.ch/vocabularies/ext/PoliticalReferenceContactPoint> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://mu.semte.ch/vocabularies/ext/politicalReferenceContactPoint> ?politicalReferenceContactPoint .
    ?politicalReferenceContactPoint ?p_p ?o_p .
  }

  FILTER NOT EXISTS {
    ?politicalReferenceContactPoint <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?contactPoint <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/ContactPoint> .
  }
}
WHERE {
  GRAPH ?g {
    ?s <http://schema.org/contactPoint> ?contactPoint .
    ?contactPoint ?p_c ?o_c .
  }

  FILTER NOT EXISTS {
    ?contactPoint <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData a <http://lblod.data.gift/vocabularies/subsidie/bestandenListingUnit/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/bestandenListingUnit> ?formData .
    ?formData ?p ?o .
    FILTER NOT EXISTS {
      ?formData a <http://lblod.data.gift/vocabularies/subsidie/bestandenListingUnit/FormData> .
    }
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData a <http://lblod.data.gift/vocabularies/subsidie/financingPartner/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://mu.semte.ch/vocabularies/ext/financingPartner> ?formData .
    ?formData ?p ?o .
    FILTER NOT EXISTS {
      ?formData a <http://lblod.data.gift/vocabularies/subsidie/financingPartner/FormData> .
    }
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData a <http://lblod.data.gift/vocabularies/subsidie/subsidieBedragListingUnit/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/subsidieBedragListingUnit> ?formData .
    ?formData ?p ?o .
    FILTER NOT EXISTS {
      ?formData a <http://lblod.data.gift/vocabularies/subsidie/subsidieBedragListingUnit/FormData> .
    }
  }
}