PREFIX m8g: <http://data.europa.eu/m8g/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# Pride evenementen
# START DATES -> 16 September 2025 - 00:00
DELETE {
  GRAPH ?g {
    ?s m8g:startTime ?oldStartTime .
  }
}
INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/periodes/ae14664f-303f-477d-aa64-4a4de4d1693e> m8g:startTime "2025-09-15T22:00:00Z"^^xsd:dateTime .
    <http://data.lblod.info/id/periodes/173c0399-a8cc-4179-98c3-4c067b810e8e> m8g:startTime "2025-09-15T22:00:00Z"^^xsd:dateTime .
  }
}
WHERE {
  GRAPH ?g {
    VALUES ?s {
      <http://data.lblod.info/id/periodes/ae14664f-303f-477d-aa64-4a4de4d1693e>
      <http://data.lblod.info/id/periodes/173c0399-a8cc-4179-98c3-4c067b810e8e>
    }
    ?s m8g:startTime ?oldStartTime .
  }
}
;
# Pride evenementen
# END DATES -> 3 October 2025 - 12:00
DELETE {
  GRAPH ?g {
    ?s m8g:endTime ?oldEndTime .
  }
}
INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/periodes/ae14664f-303f-477d-aa64-4a4de4d1693e> m8g:endTime "2025-11-03T11:00:00Z"^^xsd:dateTime .
    <http://data.lblod.info/id/periodes/173c0399-a8cc-4179-98c3-4c067b810e8e> m8g:endTime "2025-11-03T11:00:00Z"^^xsd:dateTime .
  }
}
WHERE {
  GRAPH ?g {
    VALUES ?s {
      <http://data.lblod.info/id/periodes/ae14664f-303f-477d-aa64-4a4de4d1693e>
      <http://data.lblod.info/id/periodes/173c0399-a8cc-4179-98c3-4c067b810e8e>
    }
    ?s m8g:endTime ?oldEndTime .
  }
}
;
# Pride evenementen
# Update link 
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/subsidy-measure-offers/a03196fb-5ec6-48ab-812d-bbd8daf219d1> skos:related ?oldLink .
  }
}
INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/subsidy-measure-offers/a03196fb-5ec6-48ab-812d-bbd8daf219d1> skos:related "https://www.vlaanderen.be/inclusie/projectoproep-pride-evenementen-2026" .
  }
}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/subsidy-measure-offers/a03196fb-5ec6-48ab-812d-bbd8daf219d1> skos:related ?oldLink .
  }
}
