PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/subsidy-procedural-steps/1b8434f3-349a-40c4-a6a8-979fb8e0987e> a subsidie:Subsidieprocedurestap;
      mu:uuid "1b8434f3-349a-40c4-a6a8-979fb8e0987e";
      dct:description """Subsidieaanvraag""";
      subsidie:Subsidieprocedurestap.type <http://lblod.data.gift/concepts/ee855aae-eb10-44aa-ae01-38c4f6cca0f6>;
      mobiliteit:periode  <http://data.lblod.info/id/periodes/e7e60c38-ff13-49c4-b3a3-3278f8570789>.

    # New application flow
    <http://data.lblod.info/id/subsidie-application-flows/bcede7ac-e70d-4633-b108-5ea17882d5c3> a lblodSubsidie:ApplicationFlow;
      mu:uuid "bcede7ac-e70d-4633-b108-5ea17882d5c3";
      xkos:belongsTo  <http://data.lblod.info/id/subsidy-measure-offer-series/390d055e-0be1-42fe-b4c1-dcfc4c74a13c> ;
      xkos:next <http://data.lblod.info/id/subsidie-application-flow-steps/ce0c8c48-1b57-475a-8c66-17382ef6a745> .

    <http://data.lblod.info/id/subsidie-application-flow-steps/ce0c8c48-1b57-475a-8c66-17382ef6a745> a lblodSubsidie:ApplicationStep;
      mu:uuid "ce0c8c48-1b57-475a-8c66-17382ef6a745";
      qb:order 0;
      dct:references <http://data.lblod.info/id/subsidy-procedural-steps/1b8434f3-349a-40c4-a6a8-979fb8e0987e>;
      dct:isPartOf  <http://data.lblod.info/id/subsidie-application-flows/bcede7ac-e70d-4633-b108-5ea17882d5c3>;
      dct:source <config://forms/gelijke-kansen/versions/20240709142746/form.ttl>.

    # New subsidy step periode from 15 april 2024 (midnight) to 31 mei 2025
    <http://data.lblod.info/id/periodes/e7e60c38-ff13-49c4-b3a3-3278f8570789> a <http://data.europa.eu/m8g/PeriodOfTime>;
      mu:uuid "e7e60c38-ff13-49c4-b3a3-3278f8570789";
      <http://data.europa.eu/m8g/startTime> "2024-04-14T22:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>;
      <http://data.europa.eu/m8g/endTime> "2025-05-31T21:59:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.

    # Create new subsidy and link to reeks
    <http://data.lblod.info/id/subsidy-measure-offers/848b5ca2-323f-4b98-9df1-512764ceb4e4>
      a <http://data.vlaanderen.be/ns/subsidie#SubsidiemaatregelAanbod>;
      mu:uuid "848b5ca2-323f-4b98-9df1-512764ceb4e4";
      dct:title """Gelijke kansen""";
      skos:prefLabel """Gelijke kansen""";
      <http://data.europa.eu/m8g/hasCriterion> <http://data.lblod.info/id/criterions/f5ea0615-0b0a-47db-a38c-6097ff80815d> ; # Add Gemeentes criterion (for testing purposes, can be removed later)
      <http://data.europa.eu/m8g/hasCriterion> <http://data.lblod.info/id/criterions/28fe1648-dd25-4772-b5e9-0eed4e8f4b90>> ; # Add economische actoren criterion
      cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/1b8434f3-349a-40c4-a6a8-979fb8e0987e> ;
      lblodSubsidie:heeftReeks <http://data.lblod.info/id/subsidy-measure-offer-series/390d055e-0be1-42fe-b4c1-dcfc4c74a13c> .

    # New subsidiemaatergelaanbodreeks Oproep
    <http://data.lblod.info/id/subsidy-measure-offer-series/390d055e-0be1-42fe-b4c1-dcfc4c74a13c> a lblodSubsidie:SubsidiemaatregelAanbodReeks;
      mu:uuid "390d055e-0be1-42fe-b4c1-dcfc4c74a13c";
      dct:title "Oproep"@nl;
      dct:description ""@nl ;
      common:active <http://data.lblod.info/id/subsidie-application-flows/bcede7ac-e70d-4633-b108-5ea17882d5c3> ;
      mobiliteit:periode <http://data.lblod.info/id/periodes/0a0b89ef-24a1-4da0-a0eb-13f070c474db> ;
      lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/1b8434f3-349a-40c4-a6a8-979fb8e0987e>.

    # New subsidy periode from 15 april 2024 (midnight) to 31 mei 2025
    <http://data.lblod.info/id/periodes/0a0b89ef-24a1-4da0-a0eb-13f070c474db> a <http://data.europa.eu/m8g/PeriodOfTime>;
      mu:uuid "0a0b89ef-24a1-4da0-a0eb-13f070c474db";
      <http://data.europa.eu/m8g/startTime> "2024-04-14T22:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>;
      <http://data.europa.eu/m8g/endTime> "2025-05-31T21:59:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
  }
}
