INSERT {
  GRAPH ?g {
    ?subject a <http://www.w3.org/ns/org#Organization>.
  }
}
WHERE {
  GRAPH ?g {
    ?subject a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>.
  }
  BIND(IRI(STR(?g)) AS ?g)
}
