(define-resource document-status ()
  :class (s-prefix "ext:DocumentStatus")
  :properties `((:label :string ,(s-prefix "skos:prefLabel")))
  :resource-base (s-url "http://data.lblod.info/document-statuses/")
  :features `(no-pagination-defaults include-uri)
  :on-path "document-statuses")

(define-resource file ()
  :class (s-prefix "nfo:FileDataObject")
  :properties `((:filename :string ,(s-prefix "nfo:fileName"))
                (:format :string ,(s-prefix "dct:format"))
                (:size :number ,(s-prefix "nfo:fileSize"))
                (:extension :string ,(s-prefix "dbpedia:fileExtension"))
                (:download-url :url ,(s-prefix "nie:url"))
                (:created :datetime ,(s-prefix "dct:created")))
  :has-one `((file :via ,(s-prefix "nie:dataSource")
                   :inverse t
                   :as "download")
              (file-address :via ,(s-prefix "nie:dataSource")
                            :as "data-source")
              (data-container :via ,(s-prefix "task:hasFile")
                :inverse t
                :as "data-container")
              (email :via ,(s-prefix "email:hasEmail")
                  :as "email"))
  :resource-base (s-url "http://data.lblod.info/files/")
  :features `(no-pagination-defaults include-uri)
  :on-path "files")

(define-resource email ()
  :class (s-prefix "nmo:Email")
  :properties `((:message-id :string ,(s-prefix "nmo:messageId"));; e-mail protocol-specific id: https://tools.ietf.org/html/rfc2822#section-3.6.4
                (:from :string ,(s-prefix "nmo:messageFrom"))
                (:to :string ,(s-prefix "nmo:emailTo"))
                (:cc :string ,(s-prefix "nmo:emailCc"))
                (:bcc :string ,(s-prefix "nmo:emailBcc"))
                (:subject :string ,(s-prefix "nmo:messageSubject"))
                (:content :string ,(s-prefix "nmo:plainTextMessageContent"))
                (:html-content :string ,(s-prefix "nmo:htmlMessageContent"))
                (:is-read :boolean ,(s-prefix "nmo:isRead"))
                (:content-mime-type :string ,(s-prefix "nmo:contentMimeType"))
                (:received-date :datetime ,(s-prefix "nmo:receivedDate"))
                (:sent-date :datetime ,(s-prefix "nmo:sentDate"))
                (:number-of-retries :number ,(s-prefix "task:numberOfRetries")))
  :has-one `((email :via ,(s-prefix "nmo:inReplyTo")
                    :as "in-reply-to")
             (folder :via ,(s-prefix "nmo:isPartOf")
                                   :inverse t
                                   :as "folder"))
  :has-many `((email-header :via ,(s-prefix "nmo:messageHeader")
                    :as "headers")
              (file :via ,(s-prefix "nmo:hasAttachment")
                    :as "attachments"))
  ;           (email :via ,(s-prefix "nmo:references");;https://tools.ietf.org/html/rfc2822#section-3.6.4
  ;                   :as "references"))
  :resource-base (s-url "http://data.lblod.info/id/emails/")
  :features '(include-uri)
  :on-path "emails")

(define-resource email-header ()
  :class (s-prefix "nmo:MessageHeader")
  :properties `((:header-name :string ,(s-prefix "nmo:headerName"))
                (:header-value :string ,(s-prefix "nmo:headerValue")))
  :has-one `((email :via ,(s-prefix "nmo:messageHeader")
                         :inverse t
                         :as "email"))
  :resource-base (s-url "http://data.lblod.info/id/email-headers/")
  :features '(include-uri)
  :on-path "email-headers")

(define-resource file-address ()
  :class (s-prefix "ext:FileAddress")
  :properties `((:address :url ,(s-prefix "ext:fileAddress")))
  :has-one `(
              (file :via ,(s-prefix "nie:dataSource")
                    :inverse t
                    :as "replicated-file"))
  :resource-base (s-url "http://data.lblod.info/file-addresses/")
  :features `(no-pagination-defaults include-uri)
  :on-path "file-addresses")

(define-resource remote-url ()
 :class (s-prefix "nfo:RemoteDataObject")
 :properties `((:address :url ,(s-prefix "nie:url"))
               (:created :datetime ,(s-prefix "dct:created"))
               (:modified :datetime ,(s-prefix "dct:modified"))
               (:download-status :url ,(s-prefix "adms:status"))
               (:creator :url ,(s-prefix "dct:creator"))
               )
 :has-one `(
   (file :via ,(s-prefix "nie:dataSource")
                  :inverse t
                  :as "download")
                  )
 :resource-base (s-url "http://lblod.data.gift/id/remote-urls/")
 :features `(include-uri)
 :on-path "remote-urls")
