(define-resource address ()
  :class (s-prefix "locn:Address")
  :properties `((:number :string ,(s-prefix "adres:Adresvoorstelling.huisnummer"))
                (:box-number :string ,(s-prefix "adres:Adresvoorstelling.busnummer"))
                (:street :string ,(s-prefix "locn:thoroughfare"))
                (:postcode :string ,(s-prefix "locn:postCode"))
                (:municipality :string ,(s-prefix "adres:gemeentenaam"))
                (:province :string ,(s-prefix "locn:adminUnitL2"))
                (:country :string ,(s-prefix "adres:land"))
                (:full-address :string ,(s-prefix "locn:fullAddress"))
                (:address-register-uri :url ,(s-prefix "adres:verwijstNaar")))
  :has-one `((source :via ,(s-prefix "dct:source")
                    :as "concept"))
  :resource-base (s-url "http://data.lblod.info/id/adressen/")
  :on-path "addresses")

(define-resource user ()
  :class (s-prefix "foaf:Person")
  :properties `((:first-name :string ,(s-prefix "foaf:firstName"))
                (:family-name :string ,(s-prefix "foaf:familyName")))
  :has-many `((accounts :via ,(s-prefix "foaf:account")
                        :as "account")
              (groups :via ,(s-prefix "foaf:member")
                      :as "administrative-unit"))
  :resource-base (s-url "http://data.lblod.info/id/gebruiker/")
  :on-path "users")

(define-resource account ()
  :class (s-prefix "foaf:OnlineAccount")
  :properties `((:provider :string ,(s-prefix "foaf:accountServiceHomepage"))
                (:identifier :string ,(s-prefix "dct:identifier")))
  :has-one `((user :via ,(s-prefix "foaf:account")
                   :inverse t
                   :as "user"))
  :resource-base (s-url "http://data.lblod.info/id/account/")
  :on-path "accounts")

(define-resource organization ()
  :class (s-prefix "org:Organization")
  :properties `((:name :string ,(s-prefix "skos:prefLabel"))
                (:alternative-name :string ,(s-prefix "skos:altLabel"))
                (:expected-end-date :date ,(s-prefix "lblodgeneriek:geplandeEindDatum"))
                (:last-updated :datetime ,(s-prefix "pav:lastUpdateOn"))
                (:purpose :string ,(s-prefix "org:purpose")))
  :has-many `((identifiers :via ,(s-prefix "adms:identifier")
                           :as "identifier")
              (sites :via ,(s-prefix "org:hasSite")
                     :as "site")
              (contact-points :via ,(s-prefix "schema:contactPoint")
                              :as "contact-point")
              (members :via ,(s-prefix "org:organization")
                       :inverse t
                       :as "membership")
              (change-events :via ,(s-prefix "org:resultingOrganization")
                             :inverse t
                             :as "change-event"))
  :has-one `((parent-organization :via ,(s-prefix "org:memberOf")
                                  :as "organization")
             (organization-status :via ,(s-prefix "regorg:orgStatus")
                                  :as "organization-status-code")
             (primary-site :via ,(s-prefix "org:hasPrimarySite")
                           :as "site")
             (target-audience :via ,(s-prefix "ver:doelgroep")
                              :as "target-audience"))
  :resource-base (s-url "http://data.lblod.info/id/organisaties/")
  :on-path "organizations")

(define-resource association (organization)
  :class (s-prefix "vereniging:FeitelijkeVereniging")
  :properties `((:description :string ,(s-prefix "dct:description")))
  :has-many `((activities :via ,(s-prefix "regorg:orgActivity")
                          :as "activity")
              (change-event :via ,(s-prefix "org:resultingOrganization")
                            :inverse t
                            :as "change-event")
              (recognitions :via ,(s-prefix "fv:heeftErkenning")
                            :as "recognition"))
  :has-one `((classification :via ,(s-prefix "org:classification")
                             :as "concept"))
  :resource-base (s-url "http://data.lblod.info/id/verenigingen/")
  :on-path "associations")

(define-resource person ()
  :class (s-prefix "person:Person")
  :properties `((:given-name :string ,(s-prefix "foaf:givenName"))
                (:family-name :string ,(s-prefix "foaf:familyName")))
  :has-one `((site :via ,(s-prefix "org:basedAt")
                   :as "site"))
  :resource-base (s-url "http://data.lblod.info/id/personen/")
  :on-path "persons")

(define-resource membership ()
  :class (s-prefix "org:Membership")
  :has-one `((person :via ,(s-prefix "org:member")
                     :as "person")
             (association :via ,(s-prefix "org:organization")
                          :as "association"))
  :resource-base (s-url "http://data.lblod.info/id/identificatoren/")
  :on-path "memberships")

(define-resource administrative-unit ()
  :class (s-prefix "besluit:Bestuurseenheid")
  :super `((s-prefix "organization"))
  :has-one `((classification :via ,(s-prefix "org:classification")
                             :as "administrative-unit-classification-code"))
  :resource-base (s-url "http://data.lblod.info/id/bestuurseenheden/")
  :on-path "administrative-units")

(define-resource identifier ()
  :class (s-prefix "adms:Identifier")
  :properties `((:notation :string ,(s-prefix "skos:notation"))
                (:local-name :string ,(s-prefix "skos:prefLabel")))
  :has-one `((identifier-type :via ,(s-prefix "dct:type")
                              :as "identifier-type")
             (identifying :via ,(s-prefix "adms:identified")
                          :inverse t
                          :as "organization"))
  :resource-base (s-url "http://data.lblod.info/id/identificatoren/")
  :on-path "identifiers")

(define-resource contact-point ()
  :class (s-prefix "schema:ContactPoint")
  :properties `((:honorific-prefix :language-string-set ,(s-prefix "vcard:honorific-prefix"))
                (:email :string ,(s-prefix "schema:email"))
                (:fax :string ,(s-prefix "schema:faxNumber"))
                (:name :string ,(s-prefix "foaf:name"))
                (:given-name :string ,(s-prefix "foaf:firstName"))
                (:family-name :string ,(s-prefix "foaf:familyName"))
                (:website :url ,(s-prefix "foaf:page"))
                (:phone :string ,(s-prefix "schema:telephone"))
                (:contact-type :string ,(s-prefix "schema:contactType")))
  :has-one `((address :via ,(s-prefix "locn:address")
                      :as "address")
             (secondary-contact-point :via ,(s-prefix "ext:secondaryContactPoint")
                                      :as "contact-point"))
  :has-many `((agents-in-position :via ,(s-prefix "schema:contactPoint")
                                  :inverse t
                                  :as "agent-in-position"))
  :features '(include-uri)
  :resource-base (s-url "http://data.lblod.info/id/contact-punten/")
  :on-path "contact-points")
