;; Exists in config/resources/slave-contact-domain.lisp as adres
;; (define-resource address ()
;;   :class (s-prefix "locn:Address")
;;   :properties `((:number :string ,(s-prefix "adres:Adresvoorstelling.huisnummer"))
;;                 (:box-number :string ,(s-prefix "adres:Adresvoorstelling.busnummer"))
;;                 (:street :string ,(s-prefix "locn:thoroughfare"))
;;                 (:postcode :string ,(s-prefix "locn:postCode"))
;;                 (:municipality :string ,(s-prefix "adres:gemeentenaam"))
;;                 (:province :string ,(s-prefix "locn:adminUnitL2"))
;;                 (:country :string ,(s-prefix "adres:land"))
;;                 (:full-address :string ,(s-prefix "locn:fullAddress"))
;;                 (:address-register-uri :url ,(s-prefix "adres:verwijstNaar")))
;;   :has-one `((source :via ,(s-prefix "dct:source")
;;                     :as "concept"))
;;   :resource-base (s-url "http://data.lblod.info/id/adressen/")
;;   :on-path "addresses")

;; Exists in config/resources/master-users-domain.lisp as gebruiker
;; (define-resource user ()
;;   :class (s-prefix "foaf:Person")
;;   :properties `((:first-name :string ,(s-prefix "foaf:firstName"))
;;                 (:family-name :string ,(s-prefix "foaf:familyName")))
;;   :has-many `((accounts :via ,(s-prefix "foaf:account")
;;                         :as "account")
;;               (groups :via ,(s-prefix "foaf:member")
;;                       :as "administrative-unit"))
;;   :resource-base (s-url "http://data.lblod.info/id/gebruiker/")
;;   :on-path "persons")

;; Exists in config/resources/master-users-domain.lisp as account
;; (define-resource account ()
;;   :class (s-prefix "foaf:OnlineAccount")
;;   :properties `((:provider :string ,(s-prefix "foaf:accountServiceHomepage"))
;;                 (:identifier :string ,(s-prefix "dct:identifier")))
;;   :has-one `((user :via ,(s-prefix "foaf:account")
;;                    :inverse t
;;                    :as "user"))
;;   :resource-base (s-url "http://data.lblod.info/id/account/")
;;   :on-path "accounts")

;; Exists in config/resources/worship-units.lisp as organization
;; (define-resource organization ()
;;   :class (s-prefix "org:Organization")
;;   :properties `((:name :string ,(s-prefix "skos:prefLabel"))
;;                 (:alternative-name :string ,(s-prefix "skos:altLabel"))
;;                 (:expected-end-date :date ,(s-prefix "lblodgeneriek:geplandeEindDatum"))
;;                 (:last-updated :datetime ,(s-prefix "pav:lastUpdateOn"))
;;                 (:purpose :string ,(s-prefix "org:purpose")))
;;   :has-one `((parent-organization :via ,(s-prefix "org:memberOf")
;;                                   :as "organization")
;;              (organization-status :via ,(s-prefix "regorg:orgStatus")
;;                                   :as "organization-status-code")
;;              (primary-site :via ,(s-prefix "org:hasPrimarySite")
;;                            :as "site")
;;              (target-audience :via ,(s-prefix "ver:doelgroep")
;;                               :as "target-audience"))
;;   :has-many `((identifiers :via ,(s-prefix "adms:identifier")
;;                            :as "identifier")
;;               (sites :via ,(s-prefix "org:hasSite")
;;                      :as "site")
;;               (contact-points :via ,(s-prefix "schema:contactPoint")
;;                               :as "contact-point")
;;               (members :via ,(s-prefix "org:organization")
;;                        :inverse t
;;                        :as "membership")
;;               (change-events :via ,(s-prefix "org:resultingOrganization")
;;                              :inverse t
;;                              :as "change-event"))
;;   :resource-base (s-url "http://data.lblod.info/id/organisaties/")
;;   :on-path "organizations")

(define-resource association (organization)
  :class (s-prefix "vereniging:FeitelijkeVereniging")
  :properties `((:description :string ,(s-prefix "dct:description")))
  :has-many `((activities :via ,(s-prefix "regorg:orgActivity")
                          :as "activity")
              (change-event :via ,(s-prefix "org:resultingOrganization")
                            :inverse t
                            :as "change-event")
              (recognitions :via ,(s-prefix "fv:heeftErkenning")
                            :as "recognition"))
  :has-one `((classification :via ,(s-prefix "org:classification")
                             :as "concept"))
  :resource-base (s-url "http://data.lblod.info/id/verenigingen/")
  :on-path "associations")

;; Exists in config/resources/slave-mandaat-domain.lisp as persoon
;; (define-resource person ()
;;   :class (s-prefix "person:Person")
;;   :properties `((:given-name :string ,(s-prefix "foaf:givenName"))
;;                 (:family-name :string ,(s-prefix "foaf:familyName")))
;;   :has-one `((site :via ,(s-prefix "org:basedAt")
;;                    :as "site"))
;;   :resource-base (s-url "http://data.lblod.info/id/personen/")
;;   :on-path "persons")

;; Exists in config/resources/slave-mandaat-domain.lisp as lidmaatschap
;; TODO: different resource base, is this an issue?
;; (define-resource membership ()
;;   :class (s-prefix "org:Membership")
;;   :has-one `((person :via ,(s-prefix "org:member")
;;                      :as "person")
;;              (association :via ,(s-prefix "org:organization")
;;                           :as "association"))
;;   :resource-base (s-url "http://data.lblod.info/id/identificatoren/")
;;   :on-path "memberships")

;; Exists in config/resources/slave-mandaat-domain.lisp as identificator
;; (define-resource identifier ()
;;   :class (s-prefix "adms:Identifier")
;;   :properties `((:notation :string ,(s-prefix "skos:notation"))
;;                 (:local-name :string ,(s-prefix "skos:prefLabel")))
;;   :has-one `((identifier-type :via ,(s-prefix "dct:type")
;;                               :as "identifier-type")
;;              (identifying :via ,(s-prefix "adms:identified")
;;                           :inverse t
;;                           :as "organization"))
;;   :resource-base (s-url "http://data.lblod.info/id/identificatoren/")
;;   :on-path "identifiers")

;; Exists in config/resources/slave-contact-domain.lisp as contact-punt
;; (define-resource contact-point ()
;;   :class (s-prefix "schema:ContactPoint")
;;   :properties `((:honorific-prefix :language-string-set ,(s-prefix "vcard:honorific-prefix"))
;;                 (:email :string ,(s-prefix "schema:email"))
;;                 (:fax :string ,(s-prefix "schema:faxNumber"))
;;                 (:name :string ,(s-prefix "foaf:name"))
;;                 (:given-name :string ,(s-prefix "foaf:firstName"))
;;                 (:family-name :string ,(s-prefix "foaf:familyName"))
;;                 (:website :url ,(s-prefix "foaf:page"))
;;                 (:phone :string ,(s-prefix "schema:telephone"))
;;                 (:contact-type :string ,(s-prefix "schema:contactType")))
;;   :has-one `((address :via ,(s-prefix "locn:address")
;;                       :as "address")
;;              (secondary-contact-point :via ,(s-prefix "ext:secondaryContactPoint")
;;                                       :as "contact-point"))
;;   :has-many `((agents-in-position :via ,(s-prefix "schema:contactPoint")
;;                                   :inverse t
;;                                   :as "agent-in-position"))
;;   :features '(include-uri)
;;   :resource-base (s-url "http://data.lblod.info/id/contact-punten/")
;;   :on-path "contact-points")

(define-resource activity ()
  :class (s-prefix "skos:Concept")
  :properties `((:label :string ,(s-prefix "skos:prefLabel")))
  :resource-base (s-url "http://data.lblod.info/id/identificatoren/")
  :on-path "activities"
)

(define-resource recognition ()
  :class (s-prefix "fv:Erkenning")
  :has-one `((association :via ,(s-prefix "fv:heeftErkenning")
                          :inverse t
                          :as "association"))
  :resource-base (s-url "http://data.lblod.info/id/erkenningen/")
  :on-path "recognitions"
)

;; Exists in config/resources/worship-units.lisp as site
;; (define-resource site ()
;;   :class (s-prefix "org:Site")
;;   :properties `((:description :string ,(s-prefix "dct:description")))
;;   :has-many `((contact-points :via ,(s-prefix "org:siteAddress")
;;                               :as "contact-point")
;;               (associations :via ,(s-prefix "org:hasSite")
;;                             :inverse t
;;                             :as "association"))
;;   :has-one `((address :via ,(s-prefix "organisatie:bestaatUit")
;;                       :as "address")
;;              (site-type :via ,(s-prefix "ere:vestigingstype")
;;                         :as "site-type"))
;;   :resource-base (s-url "http://data.lblod.info/id/vestigingen/")
;; )
