# FIETSTINFRASTRUCTUUR
# Validation query
# -------------------------------------------------
# SELECT DISTINCT ?tableEntry WHERE {
#   GRAPH ?g {
#      ?tableEntry a <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure#ObjectiveEntry>;
#       <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure#kilometers> ?km.
#     }
#     FILTER(REGEX(STR(?g), "^http://mu.semte.ch/graphs/organizations/.+/SubsidiepuntGebruiker$"))
# }     
# GROUP BY ?tableEntry
# HAVING (COUNT(?km) > 1)


# Gemeente Boortmeerbeek (subsidy/applications/6349C883C8723785872F9068/steps/5f6193e5-7427-4ec8-90b1-636ed5181c19/forms/6349CE8CC8723785872F906B)
DELETE DATA {
    GRAPH <http://mu.semte.ch/graphs/organizations/b942231860865ab0c4108651b117f69a755a04186df97e767707e5d95955ebbd/SubsidiepuntGebruiker> {  
        <http://lblod.data.gift/id/subsidie/bicycle-infrastructure/b3fd4117-e8c4-4cd4-9aaf-2cf3ae980ceb> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure#kilometers> 0 .
    }
}
;
# Gemeente Boortmeerbeek (subsidy/applications/6349C883C8723785872F9068/steps/5f6193e5-7427-4ec8-90b1-636ed5181c19/forms/6349CE8CC8723785872F906B)
DELETE DATA { 
    GRAPH <http://mu.semte.ch/graphs/organizations/b942231860865ab0c4108651b117f69a755a04186df97e767707e5d95955ebbd/SubsidiepuntGebruiker> {  
        <http://lblod.data.gift/id/subsidie/bicycle-infrastructure/ea1e2037-3cc7-4f06-8c80-0a70a38272d7> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure#kilometers> 0 .
    }
}
;
# Gemeente Geetbets (/subsidy/applications/6346E718C8723785872F8AE9/steps/5f6193e5-7427-4ec8-90b1-636ed5181c19/forms/6346E84AC8723785872F8AEB)
DELETE DATA {
    GRAPH <http://mu.semte.ch/graphs/organizations/243e6582a03e891c3a30a3e5db7552c83e703a609f82e1c5db8844a7ad1c8924/SubsidiepuntGebruiker> {  
        <http://lblod.data.gift/id/subsidie/bicycle-infrastructure/09d070d7-31ce-4b78-9d3b-16b753ae8cf0> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure#kilometers> 0 . 
        <http://lblod.data.gift/id/subsidie/bicycle-infrastructure/09d070d7-31ce-4b78-9d3b-16b753ae8cf0> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure#kilometers> 982.57 . 
    }
}
;
# Gemeente Menen (/subsidy/applications/6284B9CE470F7A00080000AD/steps/ad08beb8-b4a5-4a0e-ae99-1174b3b47d47/forms/62E78820470F7A000900018B)
DELETE DATA {
    GRAPH <http://mu.semte.ch/graphs/organizations/c94741a612946db4bffa00439a515a831c7d4de0d09d79538af2a1dd781500ca/SubsidiepuntGebruiker> {  
        <http://lblod.data.gift/id/subsidie/bicycle-infrastructure/1489b34c-d8e9-4488-9be3-8198407f69ec> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure#kilometers> 200 .
    }
}
;
# Gemeente Menen (/subsidy/applications/6284B9CE470F7A00080000AD/steps/ad08beb8-b4a5-4a0e-ae99-1174b3b47d47/forms/62E78820470F7A000900018B)
DELETE DATA {
    GRAPH <http://mu.semte.ch/graphs/organizations/c94741a612946db4bffa00439a515a831c7d4de0d09d79538af2a1dd781500ca/SubsidiepuntGebruiker> {  
        <http://lblod.data.gift/id/subsidie/bicycle-infrastructure/85bad695-4ba2-4c74-9ab4-831ff5b76535> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure#kilometers> 115 .
    }
}