ADD GRAPH <http://mu.semte.ch/graphs/organizations/91238ac0-26bf-11f0-84a9-6b983215480e/SubsidiepuntGebruiker> TO <http://mu.semte.ch/graphs/organizations/f380b910-a386-11f0-86bb-d36396d75bb1/SubsidiepuntGebruiker> ;
DROP SILENT GRAPH <http://mu.semte.ch/graphs/organizations/91238ac0-26bf-11f0-84a9-6b983215480e/SubsidiepuntGebruiker>
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/organisaties/91238ac0-26bf-11f0-84a9-6b983215480e> ?p ?o .
  }
}
INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/organisaties/f380b910-a386-11f0-86bb-d36396d75bb1> ?p ?o .
  }
}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/organisaties/91238ac0-26bf-11f0-84a9-6b983215480e> ?p ?o .
  }
}
;

# Reverse relationships: transfer triples where the old org is object 
DELETE {
  GRAPH ?g {
    ?s ?p <http://data.lblod.info/id/organisaties/91238ac0-26bf-11f0-84a9-6b983215480e> .
  }
}
INSERT {
  GRAPH ?g {
    ?s ?p <http://data.lblod.info/id/organisaties/f380b910-a386-11f0-86bb-d36396d75bb1> .
  }
}
WHERE {
  GRAPH ?g {
    ?s ?p <http://data.lblod.info/id/organisaties/91238ac0-26bf-11f0-84a9-6b983215480e> .
  }
}