MOVE <http://mu.semte.ch/graphs/organizations/7fbba7b0-1c63-11f0-b581-55d271ccab7d/SubsidiepuntGebruiker> TO <http://mu.semte.ch/graphs/organizations/15058360-f13c-11f0-86bb-d36396d75bb1/SubsidiepuntGebruiker>