ADD GRAPH <http://mu.semte.ch/graphs/organizations/471db4b0-211e-11f0-84a9-6b983215480e/SubsidiepuntGebruiker> TO <http://mu.semte.ch/graphs/organizations/248d1150-b455-11f0-86bb-d36396d75bb1/SubsidiepuntGebruiker> ;
DROP SILENT GRAPH <http://mu.semte.ch/graphs/organizations/471db4b0-211e-11f0-84a9-6b983215480e/SubsidiepuntGebruiker>
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/organisaties/471db4b0-211e-11f0-84a9-6b983215480e> ?p ?o .
  }
}
INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/organisaties/248d1150-b455-11f0-86bb-d36396d75bb1> ?p ?o .
  }
}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/organisaties/471db4b0-211e-11f0-84a9-6b983215480e> ?p ?o .
  }
}
;

# Reverse relationships: transfer triples where the old org is object 
DELETE {
  GRAPH ?g {
    ?s ?p <http://data.lblod.info/id/organisaties/471db4b0-211e-11f0-84a9-6b983215480e> .
  }
}
INSERT {
  GRAPH ?g {
    ?s ?p <http://data.lblod.info/id/organisaties/248d1150-b455-11f0-86bb-d36396d75bb1> .
  }
}
WHERE {
  GRAPH ?g {
    ?s ?p <http://data.lblod.info/id/organisaties/471db4b0-211e-11f0-84a9-6b983215480e> .
  }
}