PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {

    <http://lblod.data.gift/vocabularies/subsidie/ketenaanpak/TypeInzet>
      a skos:ConceptScheme ;
      mu:uuid "799a7f3f-5289-4063-90bf-fdaa529aa5a7" ;
      skos:prefLabel "Type Inzet" ;
      skos:hasTopConcept
        <http://lblod.data.gift/vocabularies/subsidie/ketenaanpak/concept/typeInzet/Personeel> ,
        <http://lblod.data.gift/vocabularies/subsidie/ketenaanpak/concept/typeInzet/Werking> .

    <http://lblod.data.gift/vocabularies/subsidie/ketenaanpak/concept/typeInzet/Personeel>
      a skos:Concept ;
      mu:uuid "a047d375-6481-4caf-9122-4d16792e06d7" ;
      skos:inScheme <http://lblod.data.gift/vocabularies/subsidie/ketenaanpak/TypeInzet> ;
      skos:prefLabel "Personeel" .

    <http://lblod.data.gift/vocabularies/subsidie/ketenaanpak/concept/typeInzet/Werking>
      a skos:Concept ;
      mu:uuid "79e258df-7921-4d86-b511-02c762257d60" ;
      skos:inScheme <http://lblod.data.gift/vocabularies/subsidie/ketenaanpak/TypeInzet> ;
      skos:prefLabel "Werking" .
  }
}
